#!/usr/bin/env python3

import argparse
import subprocess

target_issue = 'TOCDEV-7976'

parser = argparse.ArgumentParser()
parser.add_argument('package_names', nargs='+')
parser.add_argument('--custom-message')
parser.add_argument('--workspace')
parser.add_argument('-nc', '--no-commit', action='store_true')
args = parser.parse_args()

if args.workspace is None:
    subprocess.run(['yarn', 'add', '-W'] + args.package_names)
else:
    subprocess.run(['yarn', 'workspace', args.workspace, 'add'] + args.package_names)

if not args.no_commit:
    if args.custom_message is None:
        version_result = subprocess.run(['yarn', 'info', args.package_names[0], 'version'], capture_output = True, text = True)
        version = version_result.stdout.splitlines()[1]
        message = f'chore: upgrade {args.package_names[0]} to {version}'
    else:
        message = f'chore: {args.custom_message}'
    subprocess.run(['git', 'add', '*'])
    subprocess.run(['git', 'commit', '-m', message, '-m', f'Refs: {target_issue}'])
